---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-{{ $.Values.name }}-kafka-broker-reply
  namespace: knative-eventing
spec:
  action: ALLOW
  selector:
    matchLabels:
      app.kubernetes.io/component: "kafka-broker-receiver"
  rules:
    - from:
        - source:
            namespaces:
              - "knative-eventing"
            principals:
              - "cluster.local/ns/knative-eventing/sa/knative-kafka-broker-data-plane"
      to:
        - operation:
            paths:
            {{- range $v := $.Values.namespaces }}
            - "/{{ $v }}/*"
            {{- end }}
            methods: [ "POST" ]
      when:
        - key: request.headers[Kn-Namespace]
          values:
          {{- range $v := $.Values.namespaces }}
          - "{{ $v }}"
          {{- end }}
---
