{{- range $ns := $.Values.namespaces }}
---
# Allow namespace {{ $ns }} to receive requests from Knative system components, from istio-system and from all namespaces of the tenant.
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-from-knative-and-istio
  namespace: {{ $ns }}
spec:
  action: ALLOW
  rules:
{{- if $.Values.serving.enabled }}
    - from:
        - source:
            namespaces:
              {{- range $v := $.Values.namespaces }}
              - "{{ $v }}"
              {{- end }}
              - "knative-serving"
              - {{ $.Values.istioNamespace | quote }}
{{ end }}
{{- if $.Values.eventing.enabled }}
    - from:
        - source:
            namespaces:
              - "knative-eventing"
      when:
        - key: request.headers[Kn-Namespace]
          values:
          {{- range $v := $.Values.namespaces }}
          - "{{ $v }}"
          {{- end }}
{{ end }}
---
{{- end }}
