{{- range $ns := $.Values.namespaces }}
---
# Restrict namespace {{ $ns }} sidecars egress rules to tenants specific namespaces so that
# application sidecars don't consumer a ton of memory/cpu.
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
  namespace: {{ $ns }}
spec:
  egress:
    - hosts:
        {{- range $tns := $.Values.namespaces }}
        - "{{ $tns }}/*"
        {{ end }}
        - "{{ $.Values.istioNamespace }}/*"
        {{- if $.Values.serving.enabled }}
        - "knative-serving/*"
        {{ end }}
        {{- if $.Values.eventing.enabled }}
        - "knative-eventing/*"
        {{ end }}
---
{{- end }}
