{{- if .Values.eventing.enabled }}
{{- range $component := $.Values.eventing.receivers }}
---
# Allow {{ $component.name }} to receive requests from workloads and resources in {{ join "," $.Values.namespaces }}.
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-{{ $.Values.name }}-to-{{ $component.shortName }}
  namespace: knative-eventing
spec:
  action: ALLOW
  selector:
    matchLabels:
      app.kubernetes.io/component: "{{ $component.name }}"
  rules:
    # Allow to receive requests from event sources in {{ join "," $.Values.namespaces }}
    - from:
        - source:
            namespaces:
            {{- range $v := $.Values.namespaces }}
            - "{{ $v }}"
            {{- end }}
      to:
        - operation:
            paths:
            {{- range $v := $.Values.namespaces }}
            - "/{{ $v }}/*"
            {{- end }}
            methods: [ "POST" ]
        - operation:
            hosts:
            {{- range $v := $.Values.namespaces }}
            - "*.{{ $v }}.svc.{{ $.Values.cluster.domain }}"
            {{- end }}
            methods: [ "POST" ]
    - from:
        - source:
            namespaces: [ "knative-eventing" ]
            principals:
            {{- range $sa := $.Values.eventing.sendersServiceAccounts }}
            - "cluster.local/ns/knative-eventing/sa/{{ $sa.name }}"
            {{ end }}
      to:
        - operation:
            hosts:
            {{- range $v := $.Values.namespaces }}
            - "*.{{ $v }}.svc.{{ $.Values.cluster.domain }}"
            {{- end }}
            methods: [ "POST" ]
      when:
        - key: request.headers[Kn-Namespace]
          values:
          {{- range $v := $.Values.namespaces }}
          - "{{ $v }}"
          {{- end }}
    - from:
        - source:
            namespaces: [ "knative-eventing" ]
            principals:
            {{- range $sa := $.Values.eventing.sendersServiceAccounts }}
            - "cluster.local/ns/knative-eventing/sa/{{ $sa.name }}"
            {{ end }}
      to:
        - operation:
            paths:
            {{- range $v := $.Values.namespaces }}
            - "/{{ $v }}/*"
            {{- end }}
            methods: [ "POST" ]
      when:
        - key: request.headers[Kn-Namespace]
          values:
          {{- range $v := $.Values.namespaces }}
          - "{{ $v }}"
          {{- end }}
---
{{ end }}
{{ end }}