name: Build

on:
  pull_request:
    branches: [ 'main', 'release-*' ]
  push:
    branches: [ 'main', 'release-*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/setup-helm@v3
      - name: template
        run: helm template ./ --values tests/values.yaml
      - name: package
        run: helm package ./

      - name: Login to quay.io
        if: github.event_name == 'push'
        env:
          quay_user: ${{ secrets.QUAY_USER }}
          quay_password: ${{ secrets.QUAY_PASSWORD }}
        run: docker login -u="${quay_user}" -p="${quay_password}" quay.io

      - name: Push to quay.io
        if: github.event_name == 'push'
        run: ls *.tgz | xargs -I{} helm push {} oci://quay.io/openshift-knative
